// <auto-generated />
using System;
using Estacionamiento;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Estacionamiento.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Estacionamiento.Entidades.Estacionamientos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Dir")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EspMax")
                        .HasColumnType("int");

                    b.Property<float>("Tarifa")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("Estacionamientos");
                });

            modelBuilder.Entity("Estacionamiento.Entidades.Ingreso", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("Estacionamientosid")
                        .HasColumnType("int");

                    b.Property<DateTime>("HoraEntrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraSalida")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Lugarid")
                        .HasColumnType("int");

                    b.Property<float>("Monto")
                        .HasColumnType("real");

                    b.Property<int?>("Vehiculoid")
                        .HasColumnType("int");

                    b.Property<int>("idEstacionamientos")
                        .HasColumnType("int");

                    b.Property<int>("idLugar")
                        .HasColumnType("int");

                    b.Property<int>("idVehiculo")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Estacionamientosid");

                    b.HasIndex("Lugarid");

                    b.HasIndex("Vehiculoid");

                    b.ToTable("Ingreso");
                });

            modelBuilder.Entity("Estacionamiento.Entidades.Lugar", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("No")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Lugar");
                });

            modelBuilder.Entity("Estacionamiento.Entidades.Vehiculo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Matricula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Vehiculo");
                });

            modelBuilder.Entity("Estacionamiento.Entidades.Ingreso", b =>
                {
                    b.HasOne("Estacionamiento.Entidades.Estacionamientos", "Estacionamientos")
                        .WithMany()
                        .HasForeignKey("Estacionamientosid");

                    b.HasOne("Estacionamiento.Entidades.Lugar", "Lugar")
                        .WithMany()
                        .HasForeignKey("Lugarid");

                    b.HasOne("Estacionamiento.Entidades.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("Vehiculoid");

                    b.Navigation("Estacionamientos");

                    b.Navigation("Lugar");

                    b.Navigation("Vehiculo");
                });
#pragma warning restore 612, 618
        }
    }
}
